/* Generated by Yosys 0.33+6 (git sha1 31ee566ec, x86_64-w64-mingw32-g++ 9.2.1 -Os) */

(* src = "ALU_Control.v:1.1-53.10" *)
module ALU_Control(funct_i, ALUOp_i, ALUCtrl_o);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  wire _35_;
  wire _36_;
  wire _37_;
  wire _38_;
  wire _39_;
  wire _40_;
  wire _41_;
  wire _42_;
  wire _43_;
  wire _44_;
  (* src = "ALU_Control.v:9.17-9.26" *)
  output [2:0] ALUCtrl_o;
  wire [2:0] ALUCtrl_o;
  (* src = "ALU_Control.v:8.13-8.20" *)
  input [1:0] ALUOp_i;
  wire [1:0] ALUOp_i;
  (* src = "ALU_Control.v:7.13-7.20" *)
  input [9:0] funct_i;
  wire [9:0] funct_i;
  NOT _45_ (
    .A(ALUOp_i[1]),
    .Y(_00_)
  );
  NOT _46_ (
    .A(ALUOp_i[0]),
    .Y(_01_)
  );
  NOT _47_ (
    .A(funct_i[0]),
    .Y(_02_)
  );
  NOT _48_ (
    .A(funct_i[3]),
    .Y(_03_)
  );
  NOT _49_ (
    .A(funct_i[2]),
    .Y(_04_)
  );
  NOT _50_ (
    .A(funct_i[8]),
    .Y(_05_)
  );
  NOR _51_ (
    .A(ALUOp_i[1]),
    .B(_01_),
    .Y(_06_)
  );
  NAND _52_ (
    .A(_00_),
    .B(ALUOp_i[0]),
    .Y(_07_)
  );
  NOR _53_ (
    .A(funct_i[9]),
    .B(funct_i[8]),
    .Y(_08_)
  );
  NOT _54_ (
    .A(_08_),
    .Y(_09_)
  );
  NAND _55_ (
    .A(funct_i[1]),
    .B(_03_),
    .Y(_10_)
  );
  NOR _56_ (
    .A(_04_),
    .B(_10_),
    .Y(_11_)
  );
  NAND _57_ (
    .A(_08_),
    .B(_11_),
    .Y(_12_)
  );
  NOT _58_ (
    .A(_12_),
    .Y(_13_)
  );
  NOR _59_ (
    .A(funct_i[5]),
    .B(funct_i[4]),
    .Y(_14_)
  );
  NOR _60_ (
    .A(funct_i[7]),
    .B(funct_i[6]),
    .Y(_15_)
  );
  NAND _61_ (
    .A(_14_),
    .B(_15_),
    .Y(_16_)
  );
  NOT _62_ (
    .A(_16_),
    .Y(_17_)
  );
  NOR _63_ (
    .A(funct_i[0]),
    .B(_16_),
    .Y(_18_)
  );
  NOT _64_ (
    .A(_18_),
    .Y(_19_)
  );
  NOR _65_ (
    .A(_12_),
    .B(_19_),
    .Y(_20_)
  );
  NOR _66_ (
    .A(funct_i[0]),
    .B(funct_i[1]),
    .Y(_21_)
  );
  NOT _67_ (
    .A(_21_),
    .Y(_22_)
  );
  NAND _68_ (
    .A(funct_i[3]),
    .B(_04_),
    .Y(_23_)
  );
  NOR _69_ (
    .A(_09_),
    .B(_23_),
    .Y(_24_)
  );
  NAND _70_ (
    .A(_21_),
    .B(_24_),
    .Y(_25_)
  );
  NOR _71_ (
    .A(_16_),
    .B(_25_),
    .Y(_26_)
  );
  NOR _72_ (
    .A(_02_),
    .B(_16_),
    .Y(_27_)
  );
  NAND _73_ (
    .A(funct_i[0]),
    .B(_17_),
    .Y(_28_)
  );
  NOR _74_ (
    .A(_12_),
    .B(_28_),
    .Y(_29_)
  );
  NAND _75_ (
    .A(_13_),
    .B(_27_),
    .Y(_30_)
  );
  NOR _76_ (
    .A(funct_i[3]),
    .B(funct_i[2]),
    .Y(_31_)
  );
  NOR _77_ (
    .A(funct_i[9]),
    .B(_05_),
    .Y(_32_)
  );
  NAND _78_ (
    .A(_31_),
    .B(_32_),
    .Y(_33_)
  );
  NOR _79_ (
    .A(_22_),
    .B(_33_),
    .Y(_34_)
  );
  NAND _80_ (
    .A(_17_),
    .B(_34_),
    .Y(_35_)
  );
  NOR _81_ (
    .A(_26_),
    .B(_29_),
    .Y(_36_)
  );
  NAND _82_ (
    .A(_35_),
    .B(_36_),
    .Y(_37_)
  );
  NOR _83_ (
    .A(_20_),
    .B(_37_),
    .Y(_38_)
  );
  NOR _84_ (
    .A(_00_),
    .B(ALUOp_i[0]),
    .Y(_39_)
  );
  NOT _85_ (
    .A(_39_),
    .Y(_40_)
  );
  NAND _86_ (
    .A(_30_),
    .B(_39_),
    .Y(_41_)
  );
  NOR _87_ (
    .A(_38_),
    .B(_41_),
    .Y(_42_)
  );
  NOR _88_ (
    .A(_06_),
    .B(_42_),
    .Y(ALUCtrl_o[0])
  );
  NAND _89_ (
    .A(_37_),
    .B(_39_),
    .Y(_43_)
  );
  NAND _90_ (
    .A(_07_),
    .B(_43_),
    .Y(ALUCtrl_o[1])
  );
  NOR _91_ (
    .A(_20_),
    .B(_26_),
    .Y(_44_)
  );
  NOR _92_ (
    .A(_40_),
    .B(_44_),
    .Y(ALUCtrl_o[2])
  );
endmodule
