/* Generated by Yosys 0.33+6 (git sha1 31ee566ec, x86_64-w64-mingw32-g++ 9.2.1 -Os) */

(* src = "EX_Mem.v:3.1-70.10" *)
module EX_Mem(clk_i, start_i, pc_i, zero_i, ALUResult_i, VALUResult_i, RDData_i, RDaddr_i, RegWrite_i, MemToReg_i, MemRead_i, MemWrite_i, instr_i, instr_o, pc_o, zero_o, ALUResult_o, VALUResult_o, RDData_o, RDaddr_o, RegWrite_o
, MemToReg_o, MemRead_o, MemWrite_o);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  (* src = "EX_Mem.v:31.20-31.31" *)
  input [31:0] ALUResult_i;
  wire [31:0] ALUResult_i;
  (* src = "EX_Mem.v:36.21-36.32" *)
  output [31:0] ALUResult_o;
  wire [31:0] ALUResult_o;
  (* src = "EX_Mem.v:30.46-30.55" *)
  input MemRead_i;
  wire MemRead_i;
  (* src = "EX_Mem.v:35.40-35.49" *)
  output MemRead_o;
  wire MemRead_o;
  (* src = "EX_Mem.v:30.34-30.44" *)
  input MemToReg_i;
  wire MemToReg_i;
  (* src = "EX_Mem.v:35.28-35.38" *)
  output MemToReg_o;
  wire MemToReg_o;
  (* src = "EX_Mem.v:30.57-30.67" *)
  input MemWrite_i;
  wire MemWrite_i;
  (* src = "EX_Mem.v:35.51-35.61" *)
  output MemWrite_o;
  wire MemWrite_o;
  (* src = "EX_Mem.v:31.33-31.41" *)
  input [31:0] RDData_i;
  wire [31:0] RDData_i;
  (* src = "EX_Mem.v:36.34-36.42" *)
  output [31:0] RDData_o;
  wire [31:0] RDData_o;
  (* src = "EX_Mem.v:32.13-32.21" *)
  input [4:0] RDaddr_i;
  wire [4:0] RDaddr_i;
  (* src = "EX_Mem.v:37.17-37.25" *)
  output [4:0] RDaddr_o;
  wire [4:0] RDaddr_o;
  (* src = "EX_Mem.v:30.22-30.32" *)
  input RegWrite_i;
  wire RegWrite_i;
  (* src = "EX_Mem.v:35.16-35.26" *)
  output RegWrite_o;
  wire RegWrite_o;
  (* src = "EX_Mem.v:31.43-31.55" *)
  input [31:0] VALUResult_i;
  wire [31:0] VALUResult_i;
  (* src = "EX_Mem.v:36.44-36.56" *)
  output [31:0] VALUResult_o;
  wire [31:0] VALUResult_o;
  (* src = "EX_Mem.v:30.7-30.12" *)
  input clk_i;
  wire clk_i;
  (* src = "EX_Mem.v:33.15-33.22" *)
  input [31:0] instr_i;
  wire [31:0] instr_i;
  (* src = "EX_Mem.v:34.19-34.26" *)
  output [31:0] instr_o;
  wire [31:0] instr_o;
  (* src = "EX_Mem.v:31.14-31.18" *)
  input [31:0] pc_i;
  wire [31:0] pc_i;
  (* src = "EX_Mem.v:36.15-36.19" *)
  output [31:0] pc_o;
  wire [31:0] pc_o;
  (* src = "EX_Mem.v:30.69-30.76" *)
  input start_i;
  wire start_i;
  (* src = "EX_Mem.v:30.14-30.20" *)
  input zero_i;
  wire zero_i;
  (* src = "EX_Mem.v:35.8-35.14" *)
  output zero_o;
  wire zero_o;
  NOT _170_ (
    .A(start_i),
    .Y(_000_)
  );
  NOT _171_ (
    .A(start_i),
    .Y(_001_)
  );
  NOT _172_ (
    .A(start_i),
    .Y(_002_)
  );
  NOT _173_ (
    .A(start_i),
    .Y(_003_)
  );
  NOT _174_ (
    .A(start_i),
    .Y(_004_)
  );
  NOT _175_ (
    .A(start_i),
    .Y(_005_)
  );
  NOT _176_ (
    .A(start_i),
    .Y(_006_)
  );
  NOT _177_ (
    .A(start_i),
    .Y(_007_)
  );
  NOT _178_ (
    .A(start_i),
    .Y(_008_)
  );
  NOT _179_ (
    .A(start_i),
    .Y(_009_)
  );
  NOT _180_ (
    .A(start_i),
    .Y(_010_)
  );
  NOT _181_ (
    .A(start_i),
    .Y(_011_)
  );
  NOT _182_ (
    .A(start_i),
    .Y(_012_)
  );
  NOT _183_ (
    .A(start_i),
    .Y(_013_)
  );
  NOT _184_ (
    .A(start_i),
    .Y(_014_)
  );
  NOT _185_ (
    .A(start_i),
    .Y(_015_)
  );
  NOT _186_ (
    .A(start_i),
    .Y(_016_)
  );
  NOT _187_ (
    .A(start_i),
    .Y(_017_)
  );
  NOT _188_ (
    .A(start_i),
    .Y(_018_)
  );
  NOT _189_ (
    .A(start_i),
    .Y(_019_)
  );
  NOT _190_ (
    .A(start_i),
    .Y(_020_)
  );
  NOT _191_ (
    .A(start_i),
    .Y(_021_)
  );
  NOT _192_ (
    .A(start_i),
    .Y(_022_)
  );
  NOT _193_ (
    .A(start_i),
    .Y(_023_)
  );
  NOT _194_ (
    .A(start_i),
    .Y(_024_)
  );
  NOT _195_ (
    .A(start_i),
    .Y(_025_)
  );
  NOT _196_ (
    .A(start_i),
    .Y(_026_)
  );
  NOT _197_ (
    .A(start_i),
    .Y(_027_)
  );
  NOT _198_ (
    .A(start_i),
    .Y(_028_)
  );
  NOT _199_ (
    .A(start_i),
    .Y(_029_)
  );
  NOT _200_ (
    .A(start_i),
    .Y(_030_)
  );
  NOT _201_ (
    .A(start_i),
    .Y(_031_)
  );
  NOT _202_ (
    .A(start_i),
    .Y(_032_)
  );
  NOT _203_ (
    .A(start_i),
    .Y(_033_)
  );
  NOT _204_ (
    .A(start_i),
    .Y(_034_)
  );
  NOT _205_ (
    .A(start_i),
    .Y(_035_)
  );
  NOT _206_ (
    .A(start_i),
    .Y(_036_)
  );
  NOT _207_ (
    .A(start_i),
    .Y(_037_)
  );
  NOT _208_ (
    .A(start_i),
    .Y(_038_)
  );
  NOT _209_ (
    .A(start_i),
    .Y(_039_)
  );
  NOT _210_ (
    .A(start_i),
    .Y(_040_)
  );
  NOT _211_ (
    .A(start_i),
    .Y(_041_)
  );
  NOT _212_ (
    .A(start_i),
    .Y(_042_)
  );
  NOT _213_ (
    .A(start_i),
    .Y(_043_)
  );
  NOT _214_ (
    .A(start_i),
    .Y(_044_)
  );
  NOT _215_ (
    .A(start_i),
    .Y(_045_)
  );
  NOT _216_ (
    .A(start_i),
    .Y(_046_)
  );
  NOT _217_ (
    .A(start_i),
    .Y(_047_)
  );
  NOT _218_ (
    .A(start_i),
    .Y(_048_)
  );
  NOT _219_ (
    .A(start_i),
    .Y(_049_)
  );
  NOT _220_ (
    .A(start_i),
    .Y(_050_)
  );
  NOT _221_ (
    .A(start_i),
    .Y(_051_)
  );
  NOT _222_ (
    .A(start_i),
    .Y(_052_)
  );
  NOT _223_ (
    .A(start_i),
    .Y(_053_)
  );
  NOT _224_ (
    .A(start_i),
    .Y(_054_)
  );
  NOT _225_ (
    .A(start_i),
    .Y(_055_)
  );
  NOT _226_ (
    .A(start_i),
    .Y(_056_)
  );
  NOT _227_ (
    .A(start_i),
    .Y(_057_)
  );
  NOT _228_ (
    .A(start_i),
    .Y(_058_)
  );
  NOT _229_ (
    .A(start_i),
    .Y(_059_)
  );
  NOT _230_ (
    .A(start_i),
    .Y(_060_)
  );
  NOT _231_ (
    .A(start_i),
    .Y(_061_)
  );
  NOT _232_ (
    .A(start_i),
    .Y(_062_)
  );
  NOT _233_ (
    .A(start_i),
    .Y(_063_)
  );
  NOT _234_ (
    .A(start_i),
    .Y(_064_)
  );
  NOT _235_ (
    .A(start_i),
    .Y(_065_)
  );
  NOT _236_ (
    .A(start_i),
    .Y(_066_)
  );
  NOT _237_ (
    .A(start_i),
    .Y(_067_)
  );
  NOT _238_ (
    .A(start_i),
    .Y(_068_)
  );
  NOT _239_ (
    .A(start_i),
    .Y(_069_)
  );
  NOT _240_ (
    .A(start_i),
    .Y(_070_)
  );
  NOT _241_ (
    .A(start_i),
    .Y(_071_)
  );
  NOT _242_ (
    .A(start_i),
    .Y(_072_)
  );
  NOT _243_ (
    .A(start_i),
    .Y(_073_)
  );
  NOT _244_ (
    .A(start_i),
    .Y(_074_)
  );
  NOT _245_ (
    .A(start_i),
    .Y(_075_)
  );
  NOT _246_ (
    .A(start_i),
    .Y(_076_)
  );
  NOT _247_ (
    .A(start_i),
    .Y(_077_)
  );
  NOT _248_ (
    .A(start_i),
    .Y(_078_)
  );
  NOT _249_ (
    .A(start_i),
    .Y(_079_)
  );
  NOT _250_ (
    .A(start_i),
    .Y(_080_)
  );
  NOT _251_ (
    .A(start_i),
    .Y(_081_)
  );
  NOT _252_ (
    .A(start_i),
    .Y(_082_)
  );
  NOT _253_ (
    .A(start_i),
    .Y(_083_)
  );
  NOT _254_ (
    .A(start_i),
    .Y(_084_)
  );
  NOT _255_ (
    .A(start_i),
    .Y(_085_)
  );
  NOT _256_ (
    .A(start_i),
    .Y(_086_)
  );
  NOT _257_ (
    .A(start_i),
    .Y(_087_)
  );
  NOT _258_ (
    .A(start_i),
    .Y(_088_)
  );
  NOT _259_ (
    .A(start_i),
    .Y(_089_)
  );
  NOT _260_ (
    .A(start_i),
    .Y(_090_)
  );
  NOT _261_ (
    .A(start_i),
    .Y(_091_)
  );
  NOT _262_ (
    .A(start_i),
    .Y(_092_)
  );
  NOT _263_ (
    .A(start_i),
    .Y(_093_)
  );
  NOT _264_ (
    .A(start_i),
    .Y(_094_)
  );
  NOT _265_ (
    .A(start_i),
    .Y(_095_)
  );
  NOT _266_ (
    .A(start_i),
    .Y(_096_)
  );
  NOT _267_ (
    .A(start_i),
    .Y(_097_)
  );
  NOT _268_ (
    .A(start_i),
    .Y(_098_)
  );
  NOT _269_ (
    .A(start_i),
    .Y(_099_)
  );
  NOT _270_ (
    .A(start_i),
    .Y(_100_)
  );
  NOT _271_ (
    .A(start_i),
    .Y(_101_)
  );
  NOT _272_ (
    .A(start_i),
    .Y(_102_)
  );
  NOT _273_ (
    .A(start_i),
    .Y(_103_)
  );
  NOT _274_ (
    .A(start_i),
    .Y(_104_)
  );
  NOT _275_ (
    .A(start_i),
    .Y(_105_)
  );
  NOT _276_ (
    .A(start_i),
    .Y(_106_)
  );
  NOT _277_ (
    .A(start_i),
    .Y(_107_)
  );
  NOT _278_ (
    .A(start_i),
    .Y(_108_)
  );
  NOT _279_ (
    .A(start_i),
    .Y(_109_)
  );
  NOT _280_ (
    .A(start_i),
    .Y(_110_)
  );
  NOT _281_ (
    .A(start_i),
    .Y(_111_)
  );
  NOT _282_ (
    .A(start_i),
    .Y(_112_)
  );
  NOT _283_ (
    .A(start_i),
    .Y(_113_)
  );
  NOT _284_ (
    .A(start_i),
    .Y(_114_)
  );
  NOT _285_ (
    .A(start_i),
    .Y(_115_)
  );
  NOT _286_ (
    .A(start_i),
    .Y(_116_)
  );
  NOT _287_ (
    .A(start_i),
    .Y(_117_)
  );
  NOT _288_ (
    .A(start_i),
    .Y(_118_)
  );
  NOT _289_ (
    .A(start_i),
    .Y(_119_)
  );
  NOT _290_ (
    .A(start_i),
    .Y(_120_)
  );
  NOT _291_ (
    .A(start_i),
    .Y(_121_)
  );
  NOT _292_ (
    .A(start_i),
    .Y(_122_)
  );
  NOT _293_ (
    .A(start_i),
    .Y(_123_)
  );
  NOT _294_ (
    .A(start_i),
    .Y(_124_)
  );
  NOT _295_ (
    .A(start_i),
    .Y(_125_)
  );
  NOT _296_ (
    .A(start_i),
    .Y(_126_)
  );
  NOT _297_ (
    .A(start_i),
    .Y(_127_)
  );
  NOT _298_ (
    .A(start_i),
    .Y(_128_)
  );
  NOT _299_ (
    .A(start_i),
    .Y(_129_)
  );
  NOT _300_ (
    .A(start_i),
    .Y(_130_)
  );
  NOT _301_ (
    .A(start_i),
    .Y(_131_)
  );
  NOT _302_ (
    .A(start_i),
    .Y(_132_)
  );
  NOT _303_ (
    .A(start_i),
    .Y(_133_)
  );
  NOT _304_ (
    .A(start_i),
    .Y(_134_)
  );
  NOT _305_ (
    .A(start_i),
    .Y(_135_)
  );
  NOT _306_ (
    .A(start_i),
    .Y(_136_)
  );
  NOT _307_ (
    .A(start_i),
    .Y(_137_)
  );
  NOT _308_ (
    .A(start_i),
    .Y(_138_)
  );
  NOT _309_ (
    .A(start_i),
    .Y(_139_)
  );
  NOT _310_ (
    .A(start_i),
    .Y(_140_)
  );
  NOT _311_ (
    .A(start_i),
    .Y(_141_)
  );
  NOT _312_ (
    .A(start_i),
    .Y(_142_)
  );
  NOT _313_ (
    .A(start_i),
    .Y(_143_)
  );
  NOT _314_ (
    .A(start_i),
    .Y(_144_)
  );
  NOT _315_ (
    .A(start_i),
    .Y(_145_)
  );
  NOT _316_ (
    .A(start_i),
    .Y(_146_)
  );
  NOT _317_ (
    .A(start_i),
    .Y(_147_)
  );
  NOT _318_ (
    .A(start_i),
    .Y(_148_)
  );
  NOT _319_ (
    .A(start_i),
    .Y(_149_)
  );
  NOT _320_ (
    .A(start_i),
    .Y(_150_)
  );
  NOT _321_ (
    .A(start_i),
    .Y(_151_)
  );
  NOT _322_ (
    .A(start_i),
    .Y(_152_)
  );
  NOT _323_ (
    .A(start_i),
    .Y(_153_)
  );
  NOT _324_ (
    .A(start_i),
    .Y(_154_)
  );
  NOT _325_ (
    .A(start_i),
    .Y(_155_)
  );
  NOT _326_ (
    .A(start_i),
    .Y(_156_)
  );
  NOT _327_ (
    .A(start_i),
    .Y(_157_)
  );
  NOT _328_ (
    .A(start_i),
    .Y(_158_)
  );
  NOT _329_ (
    .A(start_i),
    .Y(_159_)
  );
  NOT _330_ (
    .A(start_i),
    .Y(_160_)
  );
  NOT _331_ (
    .A(start_i),
    .Y(_161_)
  );
  NOT _332_ (
    .A(start_i),
    .Y(_162_)
  );
  NOT _333_ (
    .A(start_i),
    .Y(_163_)
  );
  NOT _334_ (
    .A(start_i),
    .Y(_164_)
  );
  NOT _335_ (
    .A(start_i),
    .Y(_165_)
  );
  NOT _336_ (
    .A(start_i),
    .Y(_166_)
  );
  NOT _337_ (
    .A(start_i),
    .Y(_167_)
  );
  NOT _338_ (
    .A(start_i),
    .Y(_168_)
  );
  NOT _339_ (
    .A(start_i),
    .Y(_169_)
  );
  (* src = "EX_Mem.v:41.1-68.4" *)
  DFFSR _340_ (
    .C(clk_i),
    .D(instr_i[9]),
    .Q(instr_o[9]),
    .R(_000_),
    .S(1'h0)
  );
  (* src = "EX_Mem.v:41.1-68.4" *)
  DFFSR _341_ (
    .C(clk_i),
    .D(instr_i[10]),
    .Q(instr_o[10]),
    .R(_001_),
    .S(1'h0)
  );
  (* src = "EX_Mem.v:41.1-68.4" *)
  DFFSR _342_ (
    .C(clk_i),
    .D(instr_i[11]),
    .Q(instr_o[11]),
    .R(_002_),
    .S(1'h0)
  );
  (* src = "EX_Mem.v:41.1-68.4" *)
  DFFSR _343_ (
    .C(clk_i),
    .D(instr_i[12]),
    .Q(instr_o[12]),
    .R(_003_),
    .S(1'h0)
  );
  (* src = "EX_Mem.v:41.1-68.4" *)
  DFFSR _344_ (
    .C(clk_i),
    .D(instr_i[13]),
    .Q(instr_o[13]),
    .R(_004_),
    .S(1'h0)
  );
  (* src = "EX_Mem.v:41.1-68.4" *)
  DFFSR _345_ (
    .C(clk_i),
    .D(instr_i[14]),
    .Q(instr_o[14]),
    .R(_005_),
    .S(1'h0)
  );
  (* src = "EX_Mem.v:41.1-68.4" *)
  DFFSR _346_ (
    .C(clk_i),
    .D(instr_i[15]),
    .Q(instr_o[15]),
    .R(_006_),
    .S(1'h0)
  );
  (* src = "EX_Mem.v:41.1-68.4" *)
  DFFSR _347_ (
    .C(clk_i),
    .D(instr_i[16]),
    .Q(instr_o[16]),
    .R(_007_),
    .S(1'h0)
  );
  (* src = "EX_Mem.v:41.1-68.4" *)
  DFFSR _348_ (
    .C(clk_i),
    .D(instr_i[17]),
    .Q(instr_o[17]),
    .R(_008_),
    .S(1'h0)
  );
  (* src = "EX_Mem.v:41.1-68.4" *)
  DFFSR _349_ (
    .C(clk_i),
    .D(instr_i[18]),
    .Q(instr_o[18]),
    .R(_009_),
    .S(1'h0)
  );
  (* src = "EX_Mem.v:41.1-68.4" *)
  DFFSR _350_ (
    .C(clk_i),
    .D(instr_i[19]),
    .Q(instr_o[19]),
    .R(_010_),
    .S(1'h0)
  );
  (* src = "EX_Mem.v:41.1-68.4" *)
  DFFSR _351_ (
    .C(clk_i),
    .D(instr_i[20]),
    .Q(instr_o[20]),
    .R(_011_),
    .S(1'h0)
  );
  (* src = "EX_Mem.v:41.1-68.4" *)
  DFFSR _352_ (
    .C(clk_i),
    .D(instr_i[21]),
    .Q(instr_o[21]),
    .R(_012_),
    .S(1'h0)
  );
  (* src = "EX_Mem.v:41.1-68.4" *)
  DFFSR _353_ (
    .C(clk_i),
    .D(instr_i[22]),
    .Q(instr_o[22]),
    .R(_013_),
    .S(1'h0)
  );
  (* src = "EX_Mem.v:41.1-68.4" *)
  DFFSR _354_ (
    .C(clk_i),
    .D(instr_i[23]),
    .Q(instr_o[23]),
    .R(_014_),
    .S(1'h0)
  );
  (* src = "EX_Mem.v:41.1-68.4" *)
  DFFSR _355_ (
    .C(clk_i),
    .D(instr_i[24]),
    .Q(instr_o[24]),
    .R(_015_),
    .S(1'h0)
  );
  (* src = "EX_Mem.v:41.1-68.4" *)
  DFFSR _356_ (
    .C(clk_i),
    .D(instr_i[25]),
    .Q(instr_o[25]),
    .R(_016_),
    .S(1'h0)
  );
  (* src = "EX_Mem.v:41.1-68.4" *)
  DFFSR _357_ (
    .C(clk_i),
    .D(instr_i[26]),
    .Q(instr_o[26]),
    .R(_017_),
    .S(1'h0)
  );
  (* src = "EX_Mem.v:41.1-68.4" *)
  DFFSR _358_ (
    .C(clk_i),
    .D(instr_i[27]),
    .Q(instr_o[27]),
    .R(_018_),
    .S(1'h0)
  );
  (* src = "EX_Mem.v:41.1-68.4" *)
  DFFSR _359_ (
    .C(clk_i),
    .D(instr_i[28]),
    .Q(instr_o[28]),
    .R(_019_),
    .S(1'h0)
  );
  (* src = "EX_Mem.v:41.1-68.4" *)
  DFFSR _360_ (
    .C(clk_i),
    .D(instr_i[29]),
    .Q(instr_o[29]),
    .R(_020_),
    .S(1'h0)
  );
  (* src = "EX_Mem.v:41.1-68.4" *)
  DFFSR _361_ (
    .C(clk_i),
    .D(instr_i[30]),
    .Q(instr_o[30]),
    .R(_021_),
    .S(1'h0)
  );
  (* src = "EX_Mem.v:41.1-68.4" *)
  DFFSR _362_ (
    .C(clk_i),
    .D(instr_i[31]),
    .Q(instr_o[31]),
    .R(_022_),
    .S(1'h0)
  );
  (* src = "EX_Mem.v:41.1-68.4" *)
  DFFSR _363_ (
    .C(clk_i),
    .D(zero_i),
    .Q(zero_o),
    .R(_023_),
    .S(1'h0)
  );
  (* src = "EX_Mem.v:41.1-68.4" *)
  DFFSR _364_ (
    .C(clk_i),
    .D(RegWrite_i),
    .Q(RegWrite_o),
    .R(_024_),
    .S(1'h0)
  );
  (* src = "EX_Mem.v:41.1-68.4" *)
  DFFSR _365_ (
    .C(clk_i),
    .D(MemToReg_i),
    .Q(MemToReg_o),
    .R(_025_),
    .S(1'h0)
  );
  (* src = "EX_Mem.v:41.1-68.4" *)
  DFFSR _366_ (
    .C(clk_i),
    .D(MemRead_i),
    .Q(MemRead_o),
    .R(_026_),
    .S(1'h0)
  );
  (* src = "EX_Mem.v:41.1-68.4" *)
  DFFSR _367_ (
    .C(clk_i),
    .D(MemWrite_i),
    .Q(MemWrite_o),
    .R(_027_),
    .S(1'h0)
  );
  (* src = "EX_Mem.v:41.1-68.4" *)
  DFFSR _368_ (
    .C(clk_i),
    .D(pc_i[0]),
    .Q(pc_o[0]),
    .R(_028_),
    .S(1'h0)
  );
  (* src = "EX_Mem.v:41.1-68.4" *)
  DFFSR _369_ (
    .C(clk_i),
    .D(pc_i[1]),
    .Q(pc_o[1]),
    .R(_029_),
    .S(1'h0)
  );
  (* src = "EX_Mem.v:41.1-68.4" *)
  DFFSR _370_ (
    .C(clk_i),
    .D(pc_i[2]),
    .Q(pc_o[2]),
    .R(_030_),
    .S(1'h0)
  );
  (* src = "EX_Mem.v:41.1-68.4" *)
  DFFSR _371_ (
    .C(clk_i),
    .D(pc_i[3]),
    .Q(pc_o[3]),
    .R(_031_),
    .S(1'h0)
  );
  (* src = "EX_Mem.v:41.1-68.4" *)
  DFFSR _372_ (
    .C(clk_i),
    .D(pc_i[4]),
    .Q(pc_o[4]),
    .R(_032_),
    .S(1'h0)
  );
  (* src = "EX_Mem.v:41.1-68.4" *)
  DFFSR _373_ (
    .C(clk_i),
    .D(pc_i[5]),
    .Q(pc_o[5]),
    .R(_033_),
    .S(1'h0)
  );
  (* src = "EX_Mem.v:41.1-68.4" *)
  DFFSR _374_ (
    .C(clk_i),
    .D(pc_i[6]),
    .Q(pc_o[6]),
    .R(_034_),
    .S(1'h0)
  );
  (* src = "EX_Mem.v:41.1-68.4" *)
  DFFSR _375_ (
    .C(clk_i),
    .D(pc_i[7]),
    .Q(pc_o[7]),
    .R(_035_),
    .S(1'h0)
  );
  (* src = "EX_Mem.v:41.1-68.4" *)
  DFFSR _376_ (
    .C(clk_i),
    .D(pc_i[8]),
    .Q(pc_o[8]),
    .R(_036_),
    .S(1'h0)
  );
  (* src = "EX_Mem.v:41.1-68.4" *)
  DFFSR _377_ (
    .C(clk_i),
    .D(pc_i[9]),
    .Q(pc_o[9]),
    .R(_037_),
    .S(1'h0)
  );
  (* src = "EX_Mem.v:41.1-68.4" *)
  DFFSR _378_ (
    .C(clk_i),
    .D(pc_i[10]),
    .Q(pc_o[10]),
    .R(_038_),
    .S(1'h0)
  );
  (* src = "EX_Mem.v:41.1-68.4" *)
  DFFSR _379_ (
    .C(clk_i),
    .D(pc_i[11]),
    .Q(pc_o[11]),
    .R(_039_),
    .S(1'h0)
  );
  (* src = "EX_Mem.v:41.1-68.4" *)
  DFFSR _380_ (
    .C(clk_i),
    .D(pc_i[12]),
    .Q(pc_o[12]),
    .R(_040_),
    .S(1'h0)
  );
  (* src = "EX_Mem.v:41.1-68.4" *)
  DFFSR _381_ (
    .C(clk_i),
    .D(pc_i[13]),
    .Q(pc_o[13]),
    .R(_041_),
    .S(1'h0)
  );
  (* src = "EX_Mem.v:41.1-68.4" *)
  DFFSR _382_ (
    .C(clk_i),
    .D(pc_i[14]),
    .Q(pc_o[14]),
    .R(_042_),
    .S(1'h0)
  );
  (* src = "EX_Mem.v:41.1-68.4" *)
  DFFSR _383_ (
    .C(clk_i),
    .D(pc_i[15]),
    .Q(pc_o[15]),
    .R(_043_),
    .S(1'h0)
  );
  (* src = "EX_Mem.v:41.1-68.4" *)
  DFFSR _384_ (
    .C(clk_i),
    .D(pc_i[16]),
    .Q(pc_o[16]),
    .R(_044_),
    .S(1'h0)
  );
  (* src = "EX_Mem.v:41.1-68.4" *)
  DFFSR _385_ (
    .C(clk_i),
    .D(pc_i[17]),
    .Q(pc_o[17]),
    .R(_045_),
    .S(1'h0)
  );
  (* src = "EX_Mem.v:41.1-68.4" *)
  DFFSR _386_ (
    .C(clk_i),
    .D(pc_i[18]),
    .Q(pc_o[18]),
    .R(_046_),
    .S(1'h0)
  );
  (* src = "EX_Mem.v:41.1-68.4" *)
  DFFSR _387_ (
    .C(clk_i),
    .D(pc_i[19]),
    .Q(pc_o[19]),
    .R(_047_),
    .S(1'h0)
  );
  (* src = "EX_Mem.v:41.1-68.4" *)
  DFFSR _388_ (
    .C(clk_i),
    .D(pc_i[20]),
    .Q(pc_o[20]),
    .R(_048_),
    .S(1'h0)
  );
  (* src = "EX_Mem.v:41.1-68.4" *)
  DFFSR _389_ (
    .C(clk_i),
    .D(pc_i[21]),
    .Q(pc_o[21]),
    .R(_049_),
    .S(1'h0)
  );
  (* src = "EX_Mem.v:41.1-68.4" *)
  DFFSR _390_ (
    .C(clk_i),
    .D(pc_i[22]),
    .Q(pc_o[22]),
    .R(_050_),
    .S(1'h0)
  );
  (* src = "EX_Mem.v:41.1-68.4" *)
  DFFSR _391_ (
    .C(clk_i),
    .D(pc_i[23]),
    .Q(pc_o[23]),
    .R(_051_),
    .S(1'h0)
  );
  (* src = "EX_Mem.v:41.1-68.4" *)
  DFFSR _392_ (
    .C(clk_i),
    .D(pc_i[24]),
    .Q(pc_o[24]),
    .R(_052_),
    .S(1'h0)
  );
  (* src = "EX_Mem.v:41.1-68.4" *)
  DFFSR _393_ (
    .C(clk_i),
    .D(pc_i[25]),
    .Q(pc_o[25]),
    .R(_053_),
    .S(1'h0)
  );
  (* src = "EX_Mem.v:41.1-68.4" *)
  DFFSR _394_ (
    .C(clk_i),
    .D(pc_i[26]),
    .Q(pc_o[26]),
    .R(_054_),
    .S(1'h0)
  );
  (* src = "EX_Mem.v:41.1-68.4" *)
  DFFSR _395_ (
    .C(clk_i),
    .D(pc_i[27]),
    .Q(pc_o[27]),
    .R(_055_),
    .S(1'h0)
  );
  (* src = "EX_Mem.v:41.1-68.4" *)
  DFFSR _396_ (
    .C(clk_i),
    .D(pc_i[28]),
    .Q(pc_o[28]),
    .R(_056_),
    .S(1'h0)
  );
  (* src = "EX_Mem.v:41.1-68.4" *)
  DFFSR _397_ (
    .C(clk_i),
    .D(pc_i[29]),
    .Q(pc_o[29]),
    .R(_057_),
    .S(1'h0)
  );
  (* src = "EX_Mem.v:41.1-68.4" *)
  DFFSR _398_ (
    .C(clk_i),
    .D(pc_i[30]),
    .Q(pc_o[30]),
    .R(_058_),
    .S(1'h0)
  );
  (* src = "EX_Mem.v:41.1-68.4" *)
  DFFSR _399_ (
    .C(clk_i),
    .D(pc_i[31]),
    .Q(pc_o[31]),
    .R(_059_),
    .S(1'h0)
  );
  (* src = "EX_Mem.v:41.1-68.4" *)
  DFFSR _400_ (
    .C(clk_i),
    .D(ALUResult_i[0]),
    .Q(ALUResult_o[0]),
    .R(_060_),
    .S(1'h0)
  );
  (* src = "EX_Mem.v:41.1-68.4" *)
  DFFSR _401_ (
    .C(clk_i),
    .D(ALUResult_i[1]),
    .Q(ALUResult_o[1]),
    .R(_061_),
    .S(1'h0)
  );
  (* src = "EX_Mem.v:41.1-68.4" *)
  DFFSR _402_ (
    .C(clk_i),
    .D(ALUResult_i[2]),
    .Q(ALUResult_o[2]),
    .R(_062_),
    .S(1'h0)
  );
  (* src = "EX_Mem.v:41.1-68.4" *)
  DFFSR _403_ (
    .C(clk_i),
    .D(ALUResult_i[3]),
    .Q(ALUResult_o[3]),
    .R(_063_),
    .S(1'h0)
  );
  (* src = "EX_Mem.v:41.1-68.4" *)
  DFFSR _404_ (
    .C(clk_i),
    .D(ALUResult_i[4]),
    .Q(ALUResult_o[4]),
    .R(_064_),
    .S(1'h0)
  );
  (* src = "EX_Mem.v:41.1-68.4" *)
  DFFSR _405_ (
    .C(clk_i),
    .D(ALUResult_i[5]),
    .Q(ALUResult_o[5]),
    .R(_065_),
    .S(1'h0)
  );
  (* src = "EX_Mem.v:41.1-68.4" *)
  DFFSR _406_ (
    .C(clk_i),
    .D(ALUResult_i[6]),
    .Q(ALUResult_o[6]),
    .R(_066_),
    .S(1'h0)
  );
  (* src = "EX_Mem.v:41.1-68.4" *)
  DFFSR _407_ (
    .C(clk_i),
    .D(ALUResult_i[7]),
    .Q(ALUResult_o[7]),
    .R(_067_),
    .S(1'h0)
  );
  (* src = "EX_Mem.v:41.1-68.4" *)
  DFFSR _408_ (
    .C(clk_i),
    .D(ALUResult_i[8]),
    .Q(ALUResult_o[8]),
    .R(_068_),
    .S(1'h0)
  );
  (* src = "EX_Mem.v:41.1-68.4" *)
  DFFSR _409_ (
    .C(clk_i),
    .D(ALUResult_i[9]),
    .Q(ALUResult_o[9]),
    .R(_069_),
    .S(1'h0)
  );
  (* src = "EX_Mem.v:41.1-68.4" *)
  DFFSR _410_ (
    .C(clk_i),
    .D(ALUResult_i[10]),
    .Q(ALUResult_o[10]),
    .R(_070_),
    .S(1'h0)
  );
  (* src = "EX_Mem.v:41.1-68.4" *)
  DFFSR _411_ (
    .C(clk_i),
    .D(ALUResult_i[11]),
    .Q(ALUResult_o[11]),
    .R(_071_),
    .S(1'h0)
  );
  (* src = "EX_Mem.v:41.1-68.4" *)
  DFFSR _412_ (
    .C(clk_i),
    .D(ALUResult_i[12]),
    .Q(ALUResult_o[12]),
    .R(_072_),
    .S(1'h0)
  );
  (* src = "EX_Mem.v:41.1-68.4" *)
  DFFSR _413_ (
    .C(clk_i),
    .D(ALUResult_i[13]),
    .Q(ALUResult_o[13]),
    .R(_073_),
    .S(1'h0)
  );
  (* src = "EX_Mem.v:41.1-68.4" *)
  DFFSR _414_ (
    .C(clk_i),
    .D(ALUResult_i[14]),
    .Q(ALUResult_o[14]),
    .R(_074_),
    .S(1'h0)
  );
  (* src = "EX_Mem.v:41.1-68.4" *)
  DFFSR _415_ (
    .C(clk_i),
    .D(ALUResult_i[15]),
    .Q(ALUResult_o[15]),
    .R(_075_),
    .S(1'h0)
  );
  (* src = "EX_Mem.v:41.1-68.4" *)
  DFFSR _416_ (
    .C(clk_i),
    .D(ALUResult_i[16]),
    .Q(ALUResult_o[16]),
    .R(_076_),
    .S(1'h0)
  );
  (* src = "EX_Mem.v:41.1-68.4" *)
  DFFSR _417_ (
    .C(clk_i),
    .D(ALUResult_i[17]),
    .Q(ALUResult_o[17]),
    .R(_077_),
    .S(1'h0)
  );
  (* src = "EX_Mem.v:41.1-68.4" *)
  DFFSR _418_ (
    .C(clk_i),
    .D(ALUResult_i[18]),
    .Q(ALUResult_o[18]),
    .R(_078_),
    .S(1'h0)
  );
  (* src = "EX_Mem.v:41.1-68.4" *)
  DFFSR _419_ (
    .C(clk_i),
    .D(ALUResult_i[19]),
    .Q(ALUResult_o[19]),
    .R(_079_),
    .S(1'h0)
  );
  (* src = "EX_Mem.v:41.1-68.4" *)
  DFFSR _420_ (
    .C(clk_i),
    .D(ALUResult_i[20]),
    .Q(ALUResult_o[20]),
    .R(_080_),
    .S(1'h0)
  );
  (* src = "EX_Mem.v:41.1-68.4" *)
  DFFSR _421_ (
    .C(clk_i),
    .D(ALUResult_i[21]),
    .Q(ALUResult_o[21]),
    .R(_081_),
    .S(1'h0)
  );
  (* src = "EX_Mem.v:41.1-68.4" *)
  DFFSR _422_ (
    .C(clk_i),
    .D(ALUResult_i[22]),
    .Q(ALUResult_o[22]),
    .R(_082_),
    .S(1'h0)
  );
  (* src = "EX_Mem.v:41.1-68.4" *)
  DFFSR _423_ (
    .C(clk_i),
    .D(ALUResult_i[23]),
    .Q(ALUResult_o[23]),
    .R(_083_),
    .S(1'h0)
  );
  (* src = "EX_Mem.v:41.1-68.4" *)
  DFFSR _424_ (
    .C(clk_i),
    .D(ALUResult_i[24]),
    .Q(ALUResult_o[24]),
    .R(_084_),
    .S(1'h0)
  );
  (* src = "EX_Mem.v:41.1-68.4" *)
  DFFSR _425_ (
    .C(clk_i),
    .D(ALUResult_i[25]),
    .Q(ALUResult_o[25]),
    .R(_085_),
    .S(1'h0)
  );
  (* src = "EX_Mem.v:41.1-68.4" *)
  DFFSR _426_ (
    .C(clk_i),
    .D(ALUResult_i[26]),
    .Q(ALUResult_o[26]),
    .R(_086_),
    .S(1'h0)
  );
  (* src = "EX_Mem.v:41.1-68.4" *)
  DFFSR _427_ (
    .C(clk_i),
    .D(ALUResult_i[27]),
    .Q(ALUResult_o[27]),
    .R(_087_),
    .S(1'h0)
  );
  (* src = "EX_Mem.v:41.1-68.4" *)
  DFFSR _428_ (
    .C(clk_i),
    .D(ALUResult_i[28]),
    .Q(ALUResult_o[28]),
    .R(_088_),
    .S(1'h0)
  );
  (* src = "EX_Mem.v:41.1-68.4" *)
  DFFSR _429_ (
    .C(clk_i),
    .D(ALUResult_i[29]),
    .Q(ALUResult_o[29]),
    .R(_089_),
    .S(1'h0)
  );
  (* src = "EX_Mem.v:41.1-68.4" *)
  DFFSR _430_ (
    .C(clk_i),
    .D(ALUResult_i[30]),
    .Q(ALUResult_o[30]),
    .R(_090_),
    .S(1'h0)
  );
  (* src = "EX_Mem.v:41.1-68.4" *)
  DFFSR _431_ (
    .C(clk_i),
    .D(ALUResult_i[31]),
    .Q(ALUResult_o[31]),
    .R(_091_),
    .S(1'h0)
  );
  (* src = "EX_Mem.v:41.1-68.4" *)
  DFFSR _432_ (
    .C(clk_i),
    .D(RDData_i[0]),
    .Q(RDData_o[0]),
    .R(_092_),
    .S(1'h0)
  );
  (* src = "EX_Mem.v:41.1-68.4" *)
  DFFSR _433_ (
    .C(clk_i),
    .D(RDData_i[1]),
    .Q(RDData_o[1]),
    .R(_093_),
    .S(1'h0)
  );
  (* src = "EX_Mem.v:41.1-68.4" *)
  DFFSR _434_ (
    .C(clk_i),
    .D(RDData_i[2]),
    .Q(RDData_o[2]),
    .R(_094_),
    .S(1'h0)
  );
  (* src = "EX_Mem.v:41.1-68.4" *)
  DFFSR _435_ (
    .C(clk_i),
    .D(RDData_i[3]),
    .Q(RDData_o[3]),
    .R(_095_),
    .S(1'h0)
  );
  (* src = "EX_Mem.v:41.1-68.4" *)
  DFFSR _436_ (
    .C(clk_i),
    .D(RDData_i[4]),
    .Q(RDData_o[4]),
    .R(_096_),
    .S(1'h0)
  );
  (* src = "EX_Mem.v:41.1-68.4" *)
  DFFSR _437_ (
    .C(clk_i),
    .D(RDData_i[5]),
    .Q(RDData_o[5]),
    .R(_097_),
    .S(1'h0)
  );
  (* src = "EX_Mem.v:41.1-68.4" *)
  DFFSR _438_ (
    .C(clk_i),
    .D(RDData_i[6]),
    .Q(RDData_o[6]),
    .R(_098_),
    .S(1'h0)
  );
  (* src = "EX_Mem.v:41.1-68.4" *)
  DFFSR _439_ (
    .C(clk_i),
    .D(RDData_i[7]),
    .Q(RDData_o[7]),
    .R(_099_),
    .S(1'h0)
  );
  (* src = "EX_Mem.v:41.1-68.4" *)
  DFFSR _440_ (
    .C(clk_i),
    .D(RDData_i[8]),
    .Q(RDData_o[8]),
    .R(_100_),
    .S(1'h0)
  );
  (* src = "EX_Mem.v:41.1-68.4" *)
  DFFSR _441_ (
    .C(clk_i),
    .D(RDData_i[9]),
    .Q(RDData_o[9]),
    .R(_101_),
    .S(1'h0)
  );
  (* src = "EX_Mem.v:41.1-68.4" *)
  DFFSR _442_ (
    .C(clk_i),
    .D(RDData_i[10]),
    .Q(RDData_o[10]),
    .R(_102_),
    .S(1'h0)
  );
  (* src = "EX_Mem.v:41.1-68.4" *)
  DFFSR _443_ (
    .C(clk_i),
    .D(RDData_i[11]),
    .Q(RDData_o[11]),
    .R(_103_),
    .S(1'h0)
  );
  (* src = "EX_Mem.v:41.1-68.4" *)
  DFFSR _444_ (
    .C(clk_i),
    .D(RDData_i[12]),
    .Q(RDData_o[12]),
    .R(_104_),
    .S(1'h0)
  );
  (* src = "EX_Mem.v:41.1-68.4" *)
  DFFSR _445_ (
    .C(clk_i),
    .D(RDData_i[13]),
    .Q(RDData_o[13]),
    .R(_105_),
    .S(1'h0)
  );
  (* src = "EX_Mem.v:41.1-68.4" *)
  DFFSR _446_ (
    .C(clk_i),
    .D(RDData_i[14]),
    .Q(RDData_o[14]),
    .R(_106_),
    .S(1'h0)
  );
  (* src = "EX_Mem.v:41.1-68.4" *)
  DFFSR _447_ (
    .C(clk_i),
    .D(RDData_i[15]),
    .Q(RDData_o[15]),
    .R(_107_),
    .S(1'h0)
  );
  (* src = "EX_Mem.v:41.1-68.4" *)
  DFFSR _448_ (
    .C(clk_i),
    .D(RDData_i[16]),
    .Q(RDData_o[16]),
    .R(_108_),
    .S(1'h0)
  );
  (* src = "EX_Mem.v:41.1-68.4" *)
  DFFSR _449_ (
    .C(clk_i),
    .D(RDData_i[17]),
    .Q(RDData_o[17]),
    .R(_109_),
    .S(1'h0)
  );
  (* src = "EX_Mem.v:41.1-68.4" *)
  DFFSR _450_ (
    .C(clk_i),
    .D(RDData_i[18]),
    .Q(RDData_o[18]),
    .R(_110_),
    .S(1'h0)
  );
  (* src = "EX_Mem.v:41.1-68.4" *)
  DFFSR _451_ (
    .C(clk_i),
    .D(RDData_i[19]),
    .Q(RDData_o[19]),
    .R(_111_),
    .S(1'h0)
  );
  (* src = "EX_Mem.v:41.1-68.4" *)
  DFFSR _452_ (
    .C(clk_i),
    .D(RDData_i[20]),
    .Q(RDData_o[20]),
    .R(_112_),
    .S(1'h0)
  );
  (* src = "EX_Mem.v:41.1-68.4" *)
  DFFSR _453_ (
    .C(clk_i),
    .D(RDData_i[21]),
    .Q(RDData_o[21]),
    .R(_113_),
    .S(1'h0)
  );
  (* src = "EX_Mem.v:41.1-68.4" *)
  DFFSR _454_ (
    .C(clk_i),
    .D(RDData_i[22]),
    .Q(RDData_o[22]),
    .R(_114_),
    .S(1'h0)
  );
  (* src = "EX_Mem.v:41.1-68.4" *)
  DFFSR _455_ (
    .C(clk_i),
    .D(RDData_i[23]),
    .Q(RDData_o[23]),
    .R(_115_),
    .S(1'h0)
  );
  (* src = "EX_Mem.v:41.1-68.4" *)
  DFFSR _456_ (
    .C(clk_i),
    .D(RDData_i[24]),
    .Q(RDData_o[24]),
    .R(_116_),
    .S(1'h0)
  );
  (* src = "EX_Mem.v:41.1-68.4" *)
  DFFSR _457_ (
    .C(clk_i),
    .D(RDData_i[25]),
    .Q(RDData_o[25]),
    .R(_117_),
    .S(1'h0)
  );
  (* src = "EX_Mem.v:41.1-68.4" *)
  DFFSR _458_ (
    .C(clk_i),
    .D(RDData_i[26]),
    .Q(RDData_o[26]),
    .R(_118_),
    .S(1'h0)
  );
  (* src = "EX_Mem.v:41.1-68.4" *)
  DFFSR _459_ (
    .C(clk_i),
    .D(RDData_i[27]),
    .Q(RDData_o[27]),
    .R(_119_),
    .S(1'h0)
  );
  (* src = "EX_Mem.v:41.1-68.4" *)
  DFFSR _460_ (
    .C(clk_i),
    .D(RDData_i[28]),
    .Q(RDData_o[28]),
    .R(_120_),
    .S(1'h0)
  );
  (* src = "EX_Mem.v:41.1-68.4" *)
  DFFSR _461_ (
    .C(clk_i),
    .D(RDData_i[29]),
    .Q(RDData_o[29]),
    .R(_121_),
    .S(1'h0)
  );
  (* src = "EX_Mem.v:41.1-68.4" *)
  DFFSR _462_ (
    .C(clk_i),
    .D(RDData_i[30]),
    .Q(RDData_o[30]),
    .R(_122_),
    .S(1'h0)
  );
  (* src = "EX_Mem.v:41.1-68.4" *)
  DFFSR _463_ (
    .C(clk_i),
    .D(RDData_i[31]),
    .Q(RDData_o[31]),
    .R(_123_),
    .S(1'h0)
  );
  (* src = "EX_Mem.v:41.1-68.4" *)
  DFFSR _464_ (
    .C(clk_i),
    .D(VALUResult_i[0]),
    .Q(VALUResult_o[0]),
    .R(_124_),
    .S(1'h0)
  );
  (* src = "EX_Mem.v:41.1-68.4" *)
  DFFSR _465_ (
    .C(clk_i),
    .D(VALUResult_i[1]),
    .Q(VALUResult_o[1]),
    .R(_125_),
    .S(1'h0)
  );
  (* src = "EX_Mem.v:41.1-68.4" *)
  DFFSR _466_ (
    .C(clk_i),
    .D(VALUResult_i[2]),
    .Q(VALUResult_o[2]),
    .R(_126_),
    .S(1'h0)
  );
  (* src = "EX_Mem.v:41.1-68.4" *)
  DFFSR _467_ (
    .C(clk_i),
    .D(VALUResult_i[3]),
    .Q(VALUResult_o[3]),
    .R(_127_),
    .S(1'h0)
  );
  (* src = "EX_Mem.v:41.1-68.4" *)
  DFFSR _468_ (
    .C(clk_i),
    .D(VALUResult_i[4]),
    .Q(VALUResult_o[4]),
    .R(_128_),
    .S(1'h0)
  );
  (* src = "EX_Mem.v:41.1-68.4" *)
  DFFSR _469_ (
    .C(clk_i),
    .D(VALUResult_i[5]),
    .Q(VALUResult_o[5]),
    .R(_129_),
    .S(1'h0)
  );
  (* src = "EX_Mem.v:41.1-68.4" *)
  DFFSR _470_ (
    .C(clk_i),
    .D(VALUResult_i[6]),
    .Q(VALUResult_o[6]),
    .R(_130_),
    .S(1'h0)
  );
  (* src = "EX_Mem.v:41.1-68.4" *)
  DFFSR _471_ (
    .C(clk_i),
    .D(VALUResult_i[7]),
    .Q(VALUResult_o[7]),
    .R(_131_),
    .S(1'h0)
  );
  (* src = "EX_Mem.v:41.1-68.4" *)
  DFFSR _472_ (
    .C(clk_i),
    .D(VALUResult_i[8]),
    .Q(VALUResult_o[8]),
    .R(_132_),
    .S(1'h0)
  );
  (* src = "EX_Mem.v:41.1-68.4" *)
  DFFSR _473_ (
    .C(clk_i),
    .D(VALUResult_i[9]),
    .Q(VALUResult_o[9]),
    .R(_133_),
    .S(1'h0)
  );
  (* src = "EX_Mem.v:41.1-68.4" *)
  DFFSR _474_ (
    .C(clk_i),
    .D(VALUResult_i[10]),
    .Q(VALUResult_o[10]),
    .R(_134_),
    .S(1'h0)
  );
  (* src = "EX_Mem.v:41.1-68.4" *)
  DFFSR _475_ (
    .C(clk_i),
    .D(VALUResult_i[11]),
    .Q(VALUResult_o[11]),
    .R(_135_),
    .S(1'h0)
  );
  (* src = "EX_Mem.v:41.1-68.4" *)
  DFFSR _476_ (
    .C(clk_i),
    .D(VALUResult_i[12]),
    .Q(VALUResult_o[12]),
    .R(_136_),
    .S(1'h0)
  );
  (* src = "EX_Mem.v:41.1-68.4" *)
  DFFSR _477_ (
    .C(clk_i),
    .D(VALUResult_i[13]),
    .Q(VALUResult_o[13]),
    .R(_137_),
    .S(1'h0)
  );
  (* src = "EX_Mem.v:41.1-68.4" *)
  DFFSR _478_ (
    .C(clk_i),
    .D(VALUResult_i[14]),
    .Q(VALUResult_o[14]),
    .R(_138_),
    .S(1'h0)
  );
  (* src = "EX_Mem.v:41.1-68.4" *)
  DFFSR _479_ (
    .C(clk_i),
    .D(VALUResult_i[15]),
    .Q(VALUResult_o[15]),
    .R(_139_),
    .S(1'h0)
  );
  (* src = "EX_Mem.v:41.1-68.4" *)
  DFFSR _480_ (
    .C(clk_i),
    .D(VALUResult_i[16]),
    .Q(VALUResult_o[16]),
    .R(_140_),
    .S(1'h0)
  );
  (* src = "EX_Mem.v:41.1-68.4" *)
  DFFSR _481_ (
    .C(clk_i),
    .D(VALUResult_i[17]),
    .Q(VALUResult_o[17]),
    .R(_141_),
    .S(1'h0)
  );
  (* src = "EX_Mem.v:41.1-68.4" *)
  DFFSR _482_ (
    .C(clk_i),
    .D(VALUResult_i[18]),
    .Q(VALUResult_o[18]),
    .R(_142_),
    .S(1'h0)
  );
  (* src = "EX_Mem.v:41.1-68.4" *)
  DFFSR _483_ (
    .C(clk_i),
    .D(VALUResult_i[19]),
    .Q(VALUResult_o[19]),
    .R(_143_),
    .S(1'h0)
  );
  (* src = "EX_Mem.v:41.1-68.4" *)
  DFFSR _484_ (
    .C(clk_i),
    .D(VALUResult_i[20]),
    .Q(VALUResult_o[20]),
    .R(_144_),
    .S(1'h0)
  );
  (* src = "EX_Mem.v:41.1-68.4" *)
  DFFSR _485_ (
    .C(clk_i),
    .D(VALUResult_i[21]),
    .Q(VALUResult_o[21]),
    .R(_145_),
    .S(1'h0)
  );
  (* src = "EX_Mem.v:41.1-68.4" *)
  DFFSR _486_ (
    .C(clk_i),
    .D(VALUResult_i[22]),
    .Q(VALUResult_o[22]),
    .R(_146_),
    .S(1'h0)
  );
  (* src = "EX_Mem.v:41.1-68.4" *)
  DFFSR _487_ (
    .C(clk_i),
    .D(VALUResult_i[23]),
    .Q(VALUResult_o[23]),
    .R(_147_),
    .S(1'h0)
  );
  (* src = "EX_Mem.v:41.1-68.4" *)
  DFFSR _488_ (
    .C(clk_i),
    .D(VALUResult_i[24]),
    .Q(VALUResult_o[24]),
    .R(_148_),
    .S(1'h0)
  );
  (* src = "EX_Mem.v:41.1-68.4" *)
  DFFSR _489_ (
    .C(clk_i),
    .D(VALUResult_i[25]),
    .Q(VALUResult_o[25]),
    .R(_149_),
    .S(1'h0)
  );
  (* src = "EX_Mem.v:41.1-68.4" *)
  DFFSR _490_ (
    .C(clk_i),
    .D(VALUResult_i[26]),
    .Q(VALUResult_o[26]),
    .R(_150_),
    .S(1'h0)
  );
  (* src = "EX_Mem.v:41.1-68.4" *)
  DFFSR _491_ (
    .C(clk_i),
    .D(VALUResult_i[27]),
    .Q(VALUResult_o[27]),
    .R(_151_),
    .S(1'h0)
  );
  (* src = "EX_Mem.v:41.1-68.4" *)
  DFFSR _492_ (
    .C(clk_i),
    .D(VALUResult_i[28]),
    .Q(VALUResult_o[28]),
    .R(_152_),
    .S(1'h0)
  );
  (* src = "EX_Mem.v:41.1-68.4" *)
  DFFSR _493_ (
    .C(clk_i),
    .D(VALUResult_i[29]),
    .Q(VALUResult_o[29]),
    .R(_153_),
    .S(1'h0)
  );
  (* src = "EX_Mem.v:41.1-68.4" *)
  DFFSR _494_ (
    .C(clk_i),
    .D(VALUResult_i[30]),
    .Q(VALUResult_o[30]),
    .R(_154_),
    .S(1'h0)
  );
  (* src = "EX_Mem.v:41.1-68.4" *)
  DFFSR _495_ (
    .C(clk_i),
    .D(VALUResult_i[31]),
    .Q(VALUResult_o[31]),
    .R(_155_),
    .S(1'h0)
  );
  (* src = "EX_Mem.v:41.1-68.4" *)
  DFFSR _496_ (
    .C(clk_i),
    .D(RDaddr_i[0]),
    .Q(RDaddr_o[0]),
    .R(_156_),
    .S(1'h0)
  );
  (* src = "EX_Mem.v:41.1-68.4" *)
  DFFSR _497_ (
    .C(clk_i),
    .D(RDaddr_i[1]),
    .Q(RDaddr_o[1]),
    .R(_157_),
    .S(1'h0)
  );
  (* src = "EX_Mem.v:41.1-68.4" *)
  DFFSR _498_ (
    .C(clk_i),
    .D(RDaddr_i[2]),
    .Q(RDaddr_o[2]),
    .R(_158_),
    .S(1'h0)
  );
  (* src = "EX_Mem.v:41.1-68.4" *)
  DFFSR _499_ (
    .C(clk_i),
    .D(RDaddr_i[3]),
    .Q(RDaddr_o[3]),
    .R(_159_),
    .S(1'h0)
  );
  (* src = "EX_Mem.v:41.1-68.4" *)
  DFFSR _500_ (
    .C(clk_i),
    .D(RDaddr_i[4]),
    .Q(RDaddr_o[4]),
    .R(_160_),
    .S(1'h0)
  );
  (* src = "EX_Mem.v:41.1-68.4" *)
  DFFSR _501_ (
    .C(clk_i),
    .D(instr_i[0]),
    .Q(instr_o[0]),
    .R(_161_),
    .S(1'h0)
  );
  (* src = "EX_Mem.v:41.1-68.4" *)
  DFFSR _502_ (
    .C(clk_i),
    .D(instr_i[1]),
    .Q(instr_o[1]),
    .R(_162_),
    .S(1'h0)
  );
  (* src = "EX_Mem.v:41.1-68.4" *)
  DFFSR _503_ (
    .C(clk_i),
    .D(instr_i[2]),
    .Q(instr_o[2]),
    .R(_163_),
    .S(1'h0)
  );
  (* src = "EX_Mem.v:41.1-68.4" *)
  DFFSR _504_ (
    .C(clk_i),
    .D(instr_i[3]),
    .Q(instr_o[3]),
    .R(_164_),
    .S(1'h0)
  );
  (* src = "EX_Mem.v:41.1-68.4" *)
  DFFSR _505_ (
    .C(clk_i),
    .D(instr_i[4]),
    .Q(instr_o[4]),
    .R(_165_),
    .S(1'h0)
  );
  (* src = "EX_Mem.v:41.1-68.4" *)
  DFFSR _506_ (
    .C(clk_i),
    .D(instr_i[5]),
    .Q(instr_o[5]),
    .R(_166_),
    .S(1'h0)
  );
  (* src = "EX_Mem.v:41.1-68.4" *)
  DFFSR _507_ (
    .C(clk_i),
    .D(instr_i[6]),
    .Q(instr_o[6]),
    .R(_167_),
    .S(1'h0)
  );
  (* src = "EX_Mem.v:41.1-68.4" *)
  DFFSR _508_ (
    .C(clk_i),
    .D(instr_i[7]),
    .Q(instr_o[7]),
    .R(_168_),
    .S(1'h0)
  );
  (* src = "EX_Mem.v:41.1-68.4" *)
  DFFSR _509_ (
    .C(clk_i),
    .D(instr_i[8]),
    .Q(instr_o[8]),
    .R(_169_),
    .S(1'h0)
  );
endmodule
